
version: "2.1"
services:
  web:
    environment:
      NODE_ENV: developement
      MONGO_USER: jodel
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: jodelBookStore
      PORT: 3000
      HOST: 0.0.0.0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0

    build: .
    image: codesword/jodel-challenge
    command: start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    image: mongo
    healthcheck:
      test: echo 'db.stats().ok' | mongo --quiet || exit1
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data

volumes:
  mongo-volume:
  redis-volume: